# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161023_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproduct',
            name='image_source',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
