# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_amazonproduct_image_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonproduct',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
