# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20161023_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonProductCategory',
            fields=[
                ('product_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('parent', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='amazonsalesrank',
            name='category_id',
        ),
        migrations.AddField(
            model_name='amazonsalesrank',
            name='product_category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.AmazonProductCategory'),
            preserve_default=False,
        ),
    ]
