# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160904_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayListing',
            fields=[
                ('key', models.BigIntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=50)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Book')),
            ],
        ),
    ]
