# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20161029_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazonsalesrank',
            old_name='product_category_id',
            new_name='product_category',
        ),
    ]
