# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 19:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ebaylisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2016, 9, 11))),
                ('price', models.FloatField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.EbayListing')),
            ],
        ),
    ]
