# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20161029_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonproductcategory',
            name='parent',
            field=models.BigIntegerField(null=True),
        ),
    ]
