# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20161029_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonproductcategory',
            name='product_category_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
