# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160911_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebaylisting',
            name='author',
        ),
    ]
