# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20161029_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('shipping', models.FloatField()),
                ('used', models.BooleanField()),
                ('condition', models.CharField(choices=[(b'A', b'acceptable'), (b'G', b'good'), (b'V', b'very good'), (b'L', b'like new')], max_length=1)),
                ('is_fba', models.BooleanField()),
                ('is_featured_merchant', models.BooleanField()),
                ('seller_rating', models.IntegerField()),
                ('feedback_count', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AmazonProduct')),
            ],
        ),
    ]
