# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20161030_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonsalesrank',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='amazonsalesrank',
            unique_together=set([('product', 'product_category', 'date')]),
        ),
    ]
