# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20161030_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonsalesrank',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
