# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20161030_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonoffer',
            name='condition',
            field=models.CharField(max_length=10),
        ),
    ]
