# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20161030_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonoffer',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
