# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_amazonoffer_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonOfferPivot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.FloatField()),
                ('like_new', models.FloatField()),
                ('very_good', models.FloatField()),
                ('good', models.FloatField()),
                ('acceptable', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AmazonProduct')),
            ],
        ),
        migrations.AlterModelOptions(
            name='amazonoffer',
            options={'ordering': ('used', 'condition', 'price', 'shipping')},
        ),
        migrations.AlterModelOptions(
            name='amazonsalesrank',
            options={'verbose_name': 'Sales Rank', 'verbose_name_plural': 'Sales Rankings'},
        ),
    ]
