# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20160911_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
