# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20160911_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='foo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
