# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_amazonofferpivot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonofferpivot',
            name='acceptable',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amazonofferpivot',
            name='good',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amazonofferpivot',
            name='like_new',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amazonofferpivot',
            name='new',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amazonofferpivot',
            name='very_good',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
