# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_author_foo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='foo',
        ),
    ]
