# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20161030_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amazonsalesrank',
            options={'ordering': ('-date',), 'verbose_name': 'Sales Rank', 'verbose_name_plural': 'Sales Rankings'},
        ),
    ]
