# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_author_foo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaylisting',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='main.Author'),
        ),
    ]
