# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20160912_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='middle_name',
            field=models.CharField(blank=True, default=b'', max_length=20),
        ),
    ]
