# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_book_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, default=b'', max_length=20)),
            ],
            options={
                'ordering': ('last_name',),
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AlterUniqueTogether(
            name='authorx',
            unique_together=set([('first_name', 'last_name')]),
        ),
    ]
