# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_ebaylisting_authors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ebaylisting',
            options={'ordering': ('title',), 'verbose_name': 'Ebay Listing', 'verbose_name_plural': 'Ebay Listings'},
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='book_format',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='condition',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='language',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='synopsis',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
