# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20160918_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebaylisting',
            name='synopsis',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
