# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_ebaylisting_img_src'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebaylisting',
            old_name='img_src',
            new_name='image_source',
        ),
    ]
